[package]
name = "lionclaw"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "lionclaw"
path = "src/main.rs"

[features]
testing = []

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap = { workspace = true, features = ["derive"] }
clap_mangen = "0.2"
hex.workspace = true
lionclaw-confinement.workspace = true
lionclaw-durable-fs.workspace = true
lionclaw-model.workspace = true
lionclaw-runtime-api.workspace = true
lionclaw-runtime-acp.workspace = true
lionclaw-runtime-codex.workspace = true
reqwest = { workspace = true, features = ["rustls-tls"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde-saphyr.workspace = true
sha2.workspace = true
rustix = { workspace = true, features = ["fs", "process"] }
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "sqlite", "migrate"] }
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "fs", "net", "process", "io-util", "signal", "sync", "time"] }
toml.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
lionclaw = { path = ".", features = ["testing"] }
lionclaw-runtime-mock.workspace = true
